// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApi.Persistence.Contexts;

#nullable disable

namespace WebApi.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250702172417_mig_1")]
    partial class mig_1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApi.Domain.Entities.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("OtelId")
                        .HasColumnType("integer");

                    b.Property<string>("sifre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OtelId")
                        .IsUnique();

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("WebApi.Domain.Entities.Musteri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdiSoyadi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("WebApi.Domain.Entities.OdaTipi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Kapasite")
                        .HasColumnType("integer");

                    b.Property<string>("OdaTipiAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("OtelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OtelId");

                    b.ToTable("OdaTipleri");
                });

            modelBuilder.Entity("WebApi.Domain.Entities.Odeme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<int?>("MusteriId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OdemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RezervasyonId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Yontem")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId");

                    b.HasIndex("RezervasyonId");

                    b.ToTable("Odemeler");
                });

            modelBuilder.Entity("WebApi.Domain.Entities.Otel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdresSatiri1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OtelAdi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("Puan")
                        .HasColumnType("numeric");

                    b.Property<string>("Sehir")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Ulke")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Oteller");
                });

            modelBuilder.Entity("WebApi.Domain.Entities.Rezervasyon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CikisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<DateTime>("GirisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MusteriId")
                        .HasColumnType("integer");

                    b.Property<int>("OdaTipiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RezervasyonTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ToplamUcret")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId");

                    b.HasIndex("OdaTipiId");

                    b.ToTable("Rezervasyonlar");
                });

            modelBuilder.Entity("WebApi.Domain.Entities.Admin", b =>
                {
                    b.HasOne("WebApi.Domain.Entities.Otel", "Otel")
                        .WithOne("Admin")
                        .HasForeignKey("WebApi.Domain.Entities.Admin", "OtelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Otel");
                });

            modelBuilder.Entity("WebApi.Domain.Entities.OdaTipi", b =>
                {
                    b.HasOne("WebApi.Domain.Entities.Otel", "Otel")
                        .WithMany("OdaTipleri")
                        .HasForeignKey("OtelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Otel");
                });

            modelBuilder.Entity("WebApi.Domain.Entities.Odeme", b =>
                {
                    b.HasOne("WebApi.Domain.Entities.Musteri", null)
                        .WithMany("Odemeler")
                        .HasForeignKey("MusteriId");

                    b.HasOne("WebApi.Domain.Entities.Rezervasyon", "Rezervasyon")
                        .WithMany("Odemeler")
                        .HasForeignKey("RezervasyonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rezervasyon");
                });

            modelBuilder.Entity("WebApi.Domain.Entities.Rezervasyon", b =>
                {
                    b.HasOne("WebApi.Domain.Entities.Musteri", "Musteri")
                        .WithMany("Rezervasyonlar")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Domain.Entities.OdaTipi", "OdaTipi")
                        .WithMany()
                        .HasForeignKey("OdaTipiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musteri");

                    b.Navigation("OdaTipi");
                });

            modelBuilder.Entity("WebApi.Domain.Entities.Musteri", b =>
                {
                    b.Navigation("Odemeler");

                    b.Navigation("Rezervasyonlar");
                });

            modelBuilder.Entity("WebApi.Domain.Entities.Otel", b =>
                {
                    b.Navigation("Admin")
                        .IsRequired();

                    b.Navigation("OdaTipleri");
                });

            modelBuilder.Entity("WebApi.Domain.Entities.Rezervasyon", b =>
                {
                    b.Navigation("Odemeler");
                });
#pragma warning restore 612, 618
        }
    }
}
